/**:
    ros__parameters:
        robot_name: "msj_platform"
        model_name: "msj_platform"
        robot_model: "pinky"
        urdf_file_name: "model.urdf"
        start_controllers: ["pinky_shoulder_left_axis0", "pinky_shoulder_left_axis1", "pinky_shoulder_left_axis2",
                            "pinky_elbow_left_axis0", "pinky_elbow_left_axis1",
                            "pinky_wrist_left_axis0", "pinky_wrist_left_axis1", "pinky_wrist_left_axis2",
                            "pinky_head_axis0", "pinky_head_axis1", "pinky_head_axis2",
                            "pinky_shoulder_right_axis0", "pinky_shoulder_right_axis1", "pinky_shoulder_right_axis2",
                            "pinky_elbow_right_axis0", "pinky_elbow_right_axis1",
                            "pinky_wrist_right_axis0", "pinky_wrist_right_axis1", "pinky_wrist_right_axis2"
                            ]
        
        simulated: false
        gazebo: false
        paused: false
        use_sim_time: false
        gui: true
        headless: false
        debug: false
        external_robot_state: false
        external_robot_target: false
        x: 0
        y: 0
        z: 0
        physics: "ode"

        # TODO
        urdf_file_path:      "/home/benno/code/ros2_ws/src/ros2_control_upper_body/urdf/robody.urdf"   # ROS1 container: /roboy3/src/robots/upper_body/model.urdf
        viapoints_file_path: "/home/benno/code/ros2_ws/src/ros2_control_upper_body/urdf/cardsflow.xml" # ROS1 container: /roboy3/src/robots/upper_body/cardsflow.xml
        cardsflow_xml:       "/home/benno/code/ros2_ws/src/ros2_control_upper_body/cardsflow.xml"

        q_target: [0.0, 0.0, 0.0]
        pwm: 5.0
        m3_pwm: 5.0
        min_force: 0.0
        max_force: 100000.0
        controller: 2
        initialized: [true, true]