controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cable_length_controller:
      type: ros2_control_kindyn/CableLengthController


cable_length_controller:
  ros__parameters:
    joints:
      - shoulder_left_axis0
      - shoulder_left_axis1
      - shoulder_left_axis2
      - elbow_left_axis0
      - elbow_left_axis1    
      - wrist_left_axis0
      - wrist_left_axis1
      - wrist_left_axis2
      - head_axis0
      - head_axis1
      - head_axis2
      - shoulder_right_axis0
      - shoulder_right_axis1
      - shoulder_right_axis2
      - elbow_right_axis0
      - elbow_right_axis1
      - wrist_right_axis0
      - wrist_right_axis1
      - wrist_right_axis2
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
