controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cable_length_controller:
      #type: forward_command_controller/ForwardCommandController
      type: ros2_control_kindyn/CableLengthController

    # joint_trajectory_position_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


cable_length_controller:
  ros__parameters:
    joints:
      - elbow_left_axis0
      - elbow_left_axis1    
      - elbow_right_axis0
      - elbow_right_axis1
      - head_axis0
      - head_axis1
      - head_axis2
      - shoulder_left_axis0
      - shoulder_left_axis1
      - shoulder_left_axis2
      - shoulder_right_axis0
      - shoulder_right_axis1
      - shoulder_right_axis2
    interface_name: position # needed????????????????
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity


# joint_state_broadcaster:
#   ros__parameters:
#     joints:
#       - elbow_left_axis0
#       - elbow_left_axis1    
#       - elbow_right_axis0
#       - elbow_right_axis1
#       - head_axis0
#       - head_axis1
#       - head_axis2
#       - shoulder_left_axis0
#       - shoulder_left_axis1
#       - shoulder_left_axis2
#       - shoulder_right_axis0
#       - shoulder_right_axis1
#       - shoulder_right_axis2
#     state_interfaces:
#       - position

# joint_trajectory_position_controller:
#   ros__parameters:
#     joints:
#       - joint1
#       - joint2

#     command_interfaces:
#       - position

#     state_interfaces:
#       - position

#     state_publish_rate: 200.0 # Defaults to 50
#     action_monitor_rate: 20.0 # Defaults to 20

#     allow_partial_joints_goal: false # Defaults to false
#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true
#     constraints:
#       stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)
